// We use local filtering for bin search instead

// Algiers smart bin locations
export const smartBinLocations = [
  {
    id: "bin-1",
    name: "Didouche Mourad EcoPoint",
    nameAr: "نقطة إيكو ديدوش مراد",
    address: "Rue Didouche Mourad, Alger Centre",
    addressAr: "شارع ديدوش مراد، الجزائر الوسطى",
    lat: 36.7753,
    lng: 3.0601,
    status: "available" as const,
    fillLevel: 35,
    offer: "Double points this week!",
    offerAr: "نقاط مضاعفة هذا الأسبوع!",
    types: ["plastic", "paper", "glass"],
    neighborhood: "Alger Centre",
  },
  {
    id: "bin-2",
    name: "Hydra Green Station",
    nameAr: "محطة هيدرا الخضراء",
    address: "Boulevard des Martyrs, Hydra",
    addressAr: "شارع الشهداء، حيدرة",
    lat: 36.7456,
    lng: 3.0283,
    status: "available" as const,
    fillLevel: 52,
    offer: "Free eco bag with 100pts",
    offerAr: "حقيبة بيئية مجانية مع 100 نقطة",
    types: ["organic", "plastic", "hazardous"],
    neighborhood: "Hydra",
  },
  {
    id: "bin-3",
    name: "Bab Ezzouar Hub",
    nameAr: "مركز باب الزوار",
    address: "Université USTHB, Bab Ezzouar",
    addressAr: "جامعة هواري بومدين، باب الزوار",
    lat: 36.7089,
    lng: 3.1756,
    status: "almost_full" as const,
    fillLevel: 78,
    offer: "Student discount: +25% points",
    offerAr: "خصم الطلاب: +25% نقاط",
    types: ["paper", "plastic", "glass"],
    neighborhood: "Bab Ezzouar",
  },
  {
    id: "bin-4",
    name: "El Biar Collection Center",
    nameAr: "مركز جمع الأبيار",
    address: "Chemin Mohamed Gacem, El Biar",
    addressAr: "طريق محمد قاسم، الأبيار",
    lat: 36.7683,
    lng: 3.0317,
    status: "available" as const,
    fillLevel: 28,
    offer: "10% off partner stores",
    offerAr: "خصم 10% في المتاجر الشريكة",
    types: ["organic", "glass", "general"],
    neighborhood: "El Biar",
  },
  {
    id: "bin-5",
    name: "Bir Mourad Rais Point",
    nameAr: "نقطة بئر مراد رايس",
    address: "Avenue Ali Khodja, Bir Mourad Rais",
    addressAr: "شارع علي خوجة، بئر مراد رايس",
    lat: 36.7389,
    lng: 3.0456,
    status: "available" as const,
    fillLevel: 41,
    offer: "Weekend bonus: +50pts",
    offerAr: "مكافأة نهاية الأسبوع: +50 نقطة",
    types: ["plastic", "paper", "organic"],
    neighborhood: "Bir Mourad Rais",
  },
  {
    id: "bin-6",
    name: "Kouba Recycling Station",
    nameAr: "محطة تدوير القبة",
    address: "Rue Belkacem Amani, Kouba",
    addressAr: "شارع بلقاسم عماني، القبة",
    lat: 36.7267,
    lng: 3.0822,
    status: "full" as const,
    fillLevel: 95,
    offer: "Collection scheduled today",
    offerAr: "جمع مجدول اليوم",
    types: ["hazardous", "general", "glass"],
    neighborhood: "Kouba",
  },
  {
    id: "bin-7",
    name: "Dely Ibrahim Center",
    nameAr: "مركز دالي إبراهيم",
    address: "Route de Chéraga, Dely Ibrahim",
    addressAr: "طريق الشراقة، دالي إبراهيم",
    lat: 36.7567,
    lng: 2.9867,
    status: "available" as const,
    fillLevel: 22,
    offer: "New! Glass recycling bonus",
    offerAr: "جديد! مكافأة تدوير الزجاج",
    types: ["glass", "plastic", "paper"],
    neighborhood: "Dely Ibrahim",
  },
  {
    id: "bin-8",
    name: "Bab El Oued Station",
    nameAr: "محطة باب الواد",
    address: "Place des Martyrs, Bab El Oued",
    addressAr: "ساحة الشهداء، باب الواد",
    lat: 36.7889,
    lng: 3.0489,
    status: "almost_full" as const,
    fillLevel: 82,
    offer: "Family pack reward",
    offerAr: "مكافأة الحزمة العائلية",
    types: ["organic", "general", "plastic"],
    neighborhood: "Bab El Oued",
  },
]
